/* Runtime implementations of the fuller interaction contracts recorded with Figma. */
'use strict';
window.EXPLORATIONS = (() => {
  const KEY='fsaw.updated.v1';
  const empty=()=>({version:2,contributions:{},appearance:"portrait-original",growthIntroSeen:false,roomState:null,garden:{},spaces:{},gems:{},stories:[],contracts:{},influences:{},attachments:[]});
  let data;try{data={...empty(),...JSON.parse(localStorage.getItem(KEY)||'null')};}catch{data=empty();}
  for(const entry of Object.values(data.spaces)) if(entry.name==null) entry.name='';
  if(Object.keys(data.garden).length) data.growthIntroSeen=true;
  let pendingStoryReview=false,leafDraft=null,shelfScroll=0;
  let storyDraft=null,storyIndex=0,influenceDraft=null,selectedCategory=null,activeContract='1';
  let torch={x:170,y:570},modal=null,returnFocus=null;
  const $=s=>document.querySelector(s), view=()=>$('#view');
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const uid=()=>crypto.randomUUID();
  const asset=(name,cls='',alt='')=>`<img class="${cls}" src="assets/${name}.svg" alt="${esc(alt)}" draggable="false">`;
  const btn=(action,label,cls='btn',extra='')=>`<button type="button" class="${cls}" data-new="${action}" ${extra}>${label}</button>`;
  const field=(label,value='',name=label,placeholder='',required=false,hideLabel=false)=>`<label class="new-field"><span${hideLabel?' class="sr-only"':''}>${esc(label)}</span><textarea name="${esc(name)}" rows="2" placeholder="${esc(placeholder)}" ${required?'required':''}>${esc(value)}</textarea></label>`;
  function notify(words){let n=$('#app-notice');if(!n){n=document.createElement('div');n.id='app-notice';n.setAttribute('role','status');document.body.append(n);}n.textContent=words;clearTimeout(notify.timer);notify.timer=setTimeout(()=>{n.textContent='';},3500);}
  function save(next){try{localStorage.setItem(KEY,JSON.stringify(next));data=next;return true;}catch{if(modal?.querySelector('.dialog-error'))modal.querySelector('.dialog-error').textContent='Not saved. Your draft is still here. Please try again.';notify('There is not enough storage to keep this. Export your data or free some space, then try again.');return false;}}
  function commit(collection,id,value){const next=structuredClone(data);next[collection][id]=value;return save(next);}
  function page(id,group,title,support,body){view().innerHTML=`<section class="card updated-page" data-page="${id}" data-group="${group}"><h1 class="prompt" tabindex="-1">${title}</h1>${support?`<p class="support">${support}</p>`:''}${body}</section>`;view().querySelector('h1')?.focus({preventScroll:true});}
  function redraw(fn){NAV.withoutHistory(fn);}
  function openModal(kind,title,body,onSave){
    closeModal();returnFocus=document.activeElement;
    const d=document.createElement('dialog');d.className='illustrated-dialog '+kind;d.setAttribute('aria-labelledby','dialog-title');
    d.innerHTML=`<form class="dialog-surface"><h2 id="dialog-title">${title}</h2>${body}<p class="dialog-error" role="alert"></p><div class="btnrow"><button type="submit" class="btn">${kind==='contract-dialog'?'Keep contract':'Keep these words'}</button>${btn('close-modal','Cancel','note-act')}</div></form>`;
    document.body.append(d);modal=d;d.showModal();
    d.addEventListener('cancel',e=>{e.preventDefault();closeModal();});
    d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
    d.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.target));if(onSave(values)!==false)closeModal();});
    d.querySelector('textarea,input,button')?.focus();
  }
  function closeModal(){if(!modal)return;const d=modal;modal=null;d.close();d.remove();if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true});returnFocus=null;}
  function filledLabel(entry,fallback){return entry?.words||entry?.aspect||fallback;}

  // Six independent room entries. Confirmation is the only completion transition.
  function spaces(){
    const appearance=data.appearance||'portrait-original';
    page('spaces','spaces','In what spaces can you be yourself?','Explore the spaces where you feel free to be yourself.',
      `<div class="spaces-map spatial-scene">${asset('spaces-map-ground','scene-ground')}${appearance==='none'?'':asset('current/'+(appearance==='leaf'?'leaf-places':appearance),'map-person')}${btn('appearance','Change my appearance','btn2 appearance-button')}${DESIGN['spaces-map'].slots.map((s,i)=>`<button class="map-house" data-new="space" data-id="${s.key}" style="left:${s.x/4.28}%;top:${s.y/5.5}%" title="${esc(data.spaces[s.key]?.name||'')}" aria-label="${esc(data.spaces[s.key]?(data.spaces[s.key].name||'Unnamed space'):`Space ${i+1}: add words`)}">${asset('current/house-'+(i+1)+(data.spaces[s.key]?'':'-outline'))}<span>${esc(data.spaces[s.key]?(data.spaces[s.key].name||'Unnamed space'):'')}</span></button>`).join('')}</div><p class="note-hint">Revisit a house whenever you like. Each holds its own words.</p>${btn('keep-spaces','Keep this collection')}`);
  }
  function editSpace(id){openModal('room-dialog','A space for my self',field('Place name (optional)',data.spaces[id]?.name,'name','A name for this space…')+field('What makes room for you here?',data.spaces[id]?.words,'words','A place, person, condition, or arrangement…'),values=>{if(!values.words.trim()&&!values.name.trim()){modal.querySelector('.dialog-error').textContent='Add a place name or a few words to keep this space.';return false;}if(!commit('spaces',id,{...data.spaces[id],name:values.name,words:values.words}))return false;redraw(spaces);returnFocus=view().querySelector(`[data-new="space"][data-id="${id}"]`);notify('Your words are kept on this device.');});}
  function appearance(){
    openModal('appearance-dialog','Choose how you appear',`<div class="appearance-grid">${[['portrait-original','Original person'],['leaf','Leaf'],['star','Star'],['portrait-short','Short hair'],['portrait-silver','Silver hair'],['stickman','Stickman'],['stickman-backpack','Walking stickman with backpack'],['person-full-body','Full-body person'],['person-backpack','Walking person with backpack'],['none','No figure']].map(([id,label])=>btn('appearance-choice',`${id==='none'?'<span class="no-figure">—</span>':asset('current/'+(id==='leaf'?'leaf-places':id))}<span>${label}</span>`,'appearance-choice',`data-id="${id}" aria-pressed="${data.appearance===id}"`)).join('')}</div>`,()=>false);
    modal.querySelector('[type="submit"]').remove();
  }

  // Torch and beam are the canonical paired Figma vectors. Hit-testing uses the
  // same beam polygon in their 170x150 coordinate system, including edge overlap.
  const beamPolygon=[[29,123],[52,136],[157,58],[45,0]];
  function intersects(a,b){for(const p of [a,b])for(let i=0;i<p.length;i++){const q=p[(i+1)%p.length],n=[-(q[1]-p[i][1]),q[0]-p[i][0]];const aa=a.map(v=>v[0]*n[0]+v[1]*n[1]),bb=b.map(v=>v[0]*n[0]+v[1]*n[1]);if(Math.max(...aa)<Math.min(...bb)||Math.max(...bb)<Math.min(...aa))return false;}return true;}
  function gemLit(i){const [x,y]=DESIGN['gemstone-exploration'].positions[i];const poly=beamPolygon.map(([a,b])=>[a+torch.x-25,b+torch.y-124]);return intersects(poly,[[x,y],[x+114,y],[x+114,y+104],[x,y+104]]);}
  function gems(){
    page('gems','gems','Aspects of My Self to Explore','Things about yourself that you are curious to look into more or are thinking about. It need not be about a problem or have a clear answer.',
      `<p class="scene-instruction">Drag the torch to shine on a gemstone. While it is lit, open it to add or revisit an aspect of yourself.</p><div class="gem-scene spatial-scene"><div class="torch-beam" aria-hidden="true">${asset('gemstone-torch-beam')}</div>${DESIGN['gemstone-exploration'].positions.map(([x,y],i)=>`<button class="gem-target" data-new="gem" data-id="${i+1}" style="left:${x/4.28}%;top:${y/6.5}%" aria-label="${esc(filledLabel(data.gems[i+1],`Gemstone ${i+1}: empty`))}">${asset('current/gem-'+(i+1)+(data.gems[i+1]?'':'-outline'))}<span>${esc(data.gems[i+1]?.aspect||'')}</span></button>`).join('')}<button class="movable-torch" aria-label="Move torch. Drag, or use arrow keys; hold Shift for larger steps." type="button">${asset('current/torch')}</button></div><p class="note-hint" id="torch-status" role="status"></p><p class="note-hint">Keyboard: focus the torch and use the arrow keys. Then Tab to an illuminated gemstone and press Enter.</p>${btn('gem-attach','Bring an existing note or marker','btn2')}<div class="attached-material">${data.attachments.map(m=>`<p>${esc(m.label)} ${btn('gem-detach','Remove','note-act',`data-id="${esc(m.id)}"`)}</p>`).join('')}</div><div class="btnrow">${btn('keep-gems','Keep this exploration')}${btn('exit','Not now','note-act')}</div>`);
    const handle=$('.movable-torch');let drag=null;
    handle.addEventListener('pointerdown',e=>{e.preventDefault();const r=$('.gem-scene').getBoundingClientRect();drag={x:e.clientX,y:e.clientY,tx:torch.x,ty:torch.y,scale:428/r.width};handle.setPointerCapture(e.pointerId);});
    handle.addEventListener('pointermove',e=>{if(!drag)return;torch.x=Math.max(0,Math.min(378,drag.tx+(e.clientX-drag.x)*drag.scale));torch.y=Math.max(0,Math.min(625,drag.ty+(e.clientY-drag.y)*drag.scale));updateTorch();});
    const end=()=>drag=null;handle.addEventListener('pointerup',end);handle.addEventListener('pointercancel',end);
    handle.addEventListener('keydown',e=>{const step=e.shiftKey?30:8;const moves={ArrowLeft:[-step,0],ArrowRight:[step,0],ArrowUp:[0,-step],ArrowDown:[0,step]};if(!moves[e.key])return;e.preventDefault();torch.x=Math.max(0,Math.min(378,torch.x+moves[e.key][0]));torch.y=Math.max(0,Math.min(625,torch.y+moves[e.key][1]));updateTorch();});
    updateTorch();
  }
  function updateTorch(){const h=$('.movable-torch'),b=$('.torch-beam');if(!h||!b)return;h.style.left=(torch.x-10)/4.28+'%';h.style.top=(torch.y-10)/6.5+'%';b.style.left=(torch.x-25)/4.28+'%';b.style.top=(torch.y-124)/6.5+'%';const lit=[];view().querySelectorAll('.gem-target').forEach((el,i)=>{const on=gemLit(i);el.classList.toggle('lit',on);el.setAttribute('aria-disabled',String(!on));if(on)lit.push(i+1);});$('#torch-status').textContent=lit.length?'Illuminated: gemstone '+lit.join(', ')+'.':'Move the torch to illuminate a gemstone.';}
  function editGem(id){if(!gemLit(Number(id)-1))return;const entry=data.gems[id]||{};openModal('gem-dialog','A part/aspect of my self',field('A part/aspect of my self',entry.aspect,'aspect','What are you curious about?',true,true)+field('What draws me to it (optional)',entry.draws,'draws'),v=>{if(!v.aspect.trim())return false;if(!commit('gems',id,{aspect:v.aspect.trim(),draws:v.draws.trim()}))return false;redraw(gems);returnFocus=view().querySelector(`[data-new="gem"][data-id="${id}"]`);notify('This gemstone now holds your words.');});modal.querySelector('.dialog-surface').style.backgroundImage=`url('assets/current/gem-popup-${id}.svg')`;}

  // Stable story IDs; internal page turns never become application history stops.
  const blankStory=()=>({id:uid(),source:'',words:'',bookmark:null});
  function ensureStories(){if(!storyDraft)storyDraft=data.stories.length?structuredClone(data.stories):[blankStory(),blankStory(),blankStory()];}
  function story(){ensureStories();const s=storyDraft[storyIndex];
    page('story-book','stories','An inherited story','Something handed to you — by family, culture, a hometown, a time. You can keep, change, release, or leave it undecided.',
      `<p class="story-identity">${esc(s.source||"Story "+(storyIndex+1))}</p><div class="story-book" style="--cover-color:${["#9caa91","#b77d68","#91a7b3"][storyIndex%3]}" data-book-drop>${asset('story-book-current','book-art')}<div class="story-source"><h2>A story I inherited</h2>${field('Where did it come from?',s.source,'source','A person, place, culture, or time…')}</div><div class="story-writing">${field('The story in my words',s.words,'words','Write as little or as much as you like…')}<div class="placed-bookmark ${s.bookmark||''}">${s.bookmark?asset('current/bookmark-'+s.bookmark.toLowerCase(),'',''+s.bookmark):'No bookmark yet'}</div></div></div><p class="note-hint">Drag a bookmark onto the book, or choose one below. Release is a bookmark; it does not delete the story.</p><div class="bookmark-stacks">${['Keep','Change','Release','Undecided'].map(k=>btn('bookmark',asset('current/bookmark-'+k.toLowerCase()),'bookmark-stack '+k.toLowerCase(),`data-value="${k}" aria-label="${k} bookmark" aria-pressed="${s.bookmark===k}"`)).join('')}</div>${btn('bookmark-remove','Remove bookmark','note-act')}<nav class="story-pages" aria-label="Story pages">${btn('story-prev','← Previous','btn2',storyIndex===0?'disabled':'')}<span>Story ${storyIndex+1} of ${storyDraft.length}</span>${btn('story-next','Next →','btn2',storyIndex===storyDraft.length-1?'disabled':'')}</nav><div class="btnrow">${btn('story-add','Add a story','btn2')}${btn('story-shelf','View bookshelf','btn2')}${btn('story-save','Keep my stories')}</div><p class="note-hint">Page turns keep your draft. “Keep my stories” saves it on this device.</p>`);
    view().querySelectorAll('.story-book textarea').forEach(el=>el.addEventListener('input',()=>s[el.name]=el.value));
    view().querySelectorAll('[data-new="bookmark"]').forEach(el=>dragTo(el,'[data-book-drop]',()=>{s.bookmark=el.dataset.value;redraw(story);}));
  }
  function shelf(){ensureStories();page('story-shelf','stories','An inherited story','Each book holds a story you inherited. Open one to revisit its words or change its bookmark.',`<h2 class="serif">Your bookshelf</h2><div class="story-shelf">${storyDraft.map((s,i)=>`<button class="story-cover" data-new="story-open" data-id="${i}">${asset('current/story-'+(i%3+1))}<span><b>${esc(s.source||'Story '+(i+1))}</b><em>${esc(s.words||'A story you inherited…')}</em><small>${esc(s.bookmark||'No bookmark yet')}</small></span></button>`).join('')}</div><div class="btnrow">${btn('story-add','Add a story','btn2')}${btn('story-save','Keep my stories')}${btn('story-review','Look it over','btn2')}</div>`);}
  function keepStories(){const next=structuredClone(data);next.stories=structuredClone(storyDraft);if(save(next)){notify('Your stories and bookmarks are kept.');return true;}return false;}

  // A category drag creates one leaf; help edits the same unsaved slot.
  function garden(){const slots=Array.from({length:Math.max(4,...Object.keys(data.garden).map(Number).filter(Number.isFinite))+1},(_,i)=>String(i+1));
    const anchors=[[151.65,156.98],[214,114.87],[153.1,72.76],[218,29.98]];
    page('garden','growth','What is the Self that You Want to Grow?','Drag leaves to the plant, and jot down relationships, places, interests, feelings, experiences, memories, activities, personality traits, etc. that feel like ‘you’ on the leaves.',
      `<div class="growth-plant">${asset('current/stem','current-stem')}${asset('current/pot','current-pot')}${slots.slice(0,4).map((id,i)=>`<button class="growing-leaf ${i%2?'right':'left'} ${data.garden[id]?'filled':''}" style="left:${(anchors[i][0]-8)/4.28}%;top:${(anchors[i][1]-8)/3}%;" data-new="garden-slot" data-id="${id}" aria-label="${esc(data.garden[id]?.words||'Dotted leaf '+id+': choose a category, then place it here')}">${data.garden[id]?asset('current/leaf-'+data.garden[id].category,'saved-leaf'):asset('current/leaf-outline-'+(i+1),'empty-leaf')}<span>${esc(data.garden[id]?.words||'Example: '+['A quiet corner of the library','Drawing with no one watching','Company without conversation','Something I can’t name yet'][i])}</span></button>`).join('')}</div>${Object.keys(data.garden).length>=4?'<div class="extra-leaves">'+slots.slice(4).map(id=>btn('garden-slot',esc(data.garden[id]?.words||'+ Add another leaf'),'btn2',`data-id="${id}"`)).join('')+'</div>':''}<p class="scene-instruction" role="status">${selectedCategory?'Selected: '+esc(selectedCategory.label)+'. Choose a dotted leaf on the plant.':''}</p><div class="garden-ground spatial-scene">${DESIGN['growth-categories'].categories.map((c,i)=>{const [x,y]=[[22,4],[275,-23],[169,54],[274,118],[10,135],[238,258],[63,243],[152,161]][i];return `<div class="garden-gathering" style="left:${x/4.28}%;top:${(y+30)/4.15}%">${asset('growth-earth-patch','earth-patch')}<button class="garden-pile" data-new="garden-category" data-id="${c.key}" aria-label="Choose or drag a ${esc(c.label)} leaf"><span class="leaf-pile">${[0,1,2].map(n=>asset('current/leaf-'+c.key,'pile-leaf pile-leaf-'+n)).join('')}</span></button><span class="gathering-label">${esc(c.label)}</span></div>`;}).join('')}</div><p class="note-hint">Keep these words saves each leaf on this device.</p><div class="btnrow">${data.growthIntroSeen?btn('exit','Done for now')+btn('growth-continue','Continue guided exploration','btn2'):btn('growth-continue','Continue')+btn('growth-continue','Skip this','note-act')+btn('keep-garden','Keep this collection','btn2')}</div>`);
    view().querySelectorAll('.garden-pile').forEach(el=>dragTo(el,'.growing-leaf',target=>{if(data.garden[target.dataset.id])return;selectedCategory=DESIGN['growth-categories'].categories.find(c=>c.key===el.dataset.id);editLeaf(target.dataset.id);},'current/leaf-'+el.dataset.id));
  }
  function editLeaf(id,restore=false){const old=data.garden[id],c=restore?leafDraft.category:old?DESIGN['growth-categories'].categories.find(c=>c.key===old.category):selectedCategory;if(!c){notify('Choose a leaf pile first.');return;}if(!restore)leafDraft={id,category:c,words:old?.words||''};
    openModal('leaf-dialog',esc(c.label),field('What would you like to grow?',leafDraft.words,'words','Your own words…',true)+btn('garden-language','Help me find language','btn2',`data-id="${c.key}"`),v=>{if(!v.words.trim())return false;if(!commit('garden',id,{category:c.key,color:c.color,words:v.words}))return false;leafDraft=null;selectedCategory=null;redraw(garden);returnFocus=view().querySelector(`[data-new="garden-slot"][data-id="${id}"]`);notify('Your words are kept on this device.');});
    modal.querySelector('.dialog-surface').style.backgroundColor=ITERATION_DATA.leafColors[c.key];
  }
  const language={people:['Company without conversation','A friendship where I can be myself','Community that makes room for me'],places:['A quiet corner of the library','Time in nature','A room with morning light'],interests:['Drawing with no one watching','Something I am curious about','An interest without an outcome'],feelings:['Space for contradictory feelings','A little more ease','Feeling understood'],memories:['A memory I want to revisit','An experience that shaped me'],activities:['Making something with my hands','Moving in a way that feels good'],traits:['My curiosity','My sensitivity','A part of me I am learning to value'],others:['Something I cannot name yet','Something of my own']};
  function languagePicker(key){if(!leafDraft)return;leafDraft.words=modal.querySelector('[name="words"]').value;const parent=modal,focus=document.activeElement;const d=document.createElement('dialog');d.className='illustrated-dialog language-dialog';d.innerHTML=`<form class="dialog-surface"><h2>Help me find language</h2><p>${esc(leafDraft.category.label)}</p><div class="language-options">${language[key].map(s=>`<button type="button" class="btn2" data-suggestion="${esc(s)}">${esc(s)}</button>`).join('')}</div>${field('My words',leafDraft.words,'words','Choose some words or write your own.')}<div class="btnrow"><button class="btn" type="submit">Use these words</button><button class="note-act" type="button" data-language-back>Back to leaf</button></div></form>`;document.body.append(d);d.showModal();const close=()=>{d.close();d.remove();focus.focus();};d.addEventListener('cancel',e=>{e.preventDefault();close();});d.addEventListener('click',e=>{const b=e.target.closest('[data-suggestion]');if(b)d.querySelector('textarea').value=b.dataset.suggestion;if(e.target.closest('[data-language-back]')||e.target===d)close();});d.querySelector('form').onsubmit=e=>{e.preventDefault();leafDraft.words=d.querySelector('textarea').value;parent.querySelector('textarea').value=leafDraft.words;close();};}
  // Only the currently picked-up object is retained by global cancellation.
  // Detached page controls keep their own listeners and can be garbage-collected.
  let cancelActiveDrag=null;
  function dragTo(el,selector,drop,preview){
    let drag=null,timer;el.style.touchAction='auto';
    const clean=()=>{clearTimeout(timer);drag?.ghost?.remove();document.querySelectorAll('.store-drop-active').forEach(x=>x.classList.remove('store-drop-active'));drag=null;if(cancelActiveDrag===cancel)cancelActiveDrag=null;};
    const suppress=()=>{el.dataset.suppressClick='yes';setTimeout(()=>delete el.dataset.suppressClick,300);};
    const cancel=()=>{if(drag){suppress();clean();}};
    const down=(e,touch=false)=>{cancelActiveDrag?.();cancelActiveDrag=cancel;drag={x:e.clientX,y:e.clientY,moved:false,ghost:null,ready:!touch,touch};if(touch)timer=setTimeout(()=>{if(drag)drag.ready=true;},250);else{e.preventDefault();el.setPointerCapture(e.pointerId);}};
    const move=e=>{if(!drag)return;const distance=Math.hypot(e.clientX-drag.x,e.clientY-drag.y);if(!drag.ready){if(distance>6)clean();return;}if(distance>6)drag.moved=true;if(!drag.moved)return;if(!drag.ghost){drag.ghost=document.createElement('div');drag.ghost.innerHTML=preview?asset(preview):el.classList.contains('store-basket')?el.parentElement.innerHTML:el.innerHTML;drag.ghost.className='drag-preview';document.body.append(drag.ghost);}document.querySelectorAll('.store-drop-active').forEach(x=>x.classList.remove('store-drop-active'));document.elementFromPoint(e.clientX,e.clientY)?.closest(selector)?.classList.add('store-drop-active');drag.ghost.style.left=e.clientX+'px';drag.ghost.style.top=e.clientY+'px';if(e.clientY<60)window.scrollBy(0,-12);if(e.clientY>innerHeight-60)window.scrollBy(0,12);};
    const finish=e=>{if(!drag)return;const moved=drag.moved;clean();if(moved){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest(selector);suppress();if(target)drop(target);}};
    el.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch'&&e.button===0)down(e);});el.addEventListener('pointermove',e=>{if(e.pointerType!=='touch'){if(drag)e.preventDefault();move(e);}});el.addEventListener('pointerup',e=>{if(e.pointerType!=='touch')finish(e);});el.addEventListener('pointercancel',e=>{if(e.pointerType!=='touch')clean();});
    el.addEventListener('touchstart',e=>{if(e.touches.length===1)down(e.touches[0],true);},{passive:true});el.addEventListener('touchmove',e=>{if(drag?.ready&&e.cancelable)e.preventDefault();if(e.touches.length===1)move(e.touches[0]);},{passive:false});el.addEventListener('touchend',e=>{if(drag?.moved&&e.cancelable)e.preventDefault();if(e.changedTouches[0])finish(e.changedTouches[0]);},{passive:false});el.addEventListener('touchcancel',clean);
  }

  function influences(){if(!influenceDraft)influenceDraft=structuredClone(data.influences);page('influences','influences','An influence','People, works, or places that helped you grow—or make you think, “I want to be a little more like that.” Write a name, a title, or a few words on any object. One is enough; you can use more than one.',`<div class="influence-objects">${DESIGN['influence-writing-objects'].items.map(item=>`<div class="influence-object">${asset('current/influence-'+item.key)}${item.fields.map((f,i)=>`<textarea aria-label="${esc(item.name+' '+(i+1))}" data-influence="${item.key}-${i}" style="left:${f.x/2.06}%;top:${f.y/1.84}%;width:${f.w/2.06}%;height:${f.h/1.84}%" placeholder="${esc(f.text)}">${esc(influenceDraft[item.key+'-'+i]||'')}</textarea>`).join('')}</div>`).join('')}</div><div class="btnrow">${btn('influence-continue','Continue')}${btn('influence-save','Keep these influences','btn2')}${btn('influence-continue','Skip to the sorting','note-act')}</div>`);view().querySelectorAll('[data-influence]').forEach(el=>el.addEventListener('input',()=>influenceDraft[el.dataset.influence]=el.value));}

  // Nine individually saved scrolls, with independent, optional continuous ratings.
  function contracts(){page('contracts','community','Communities: Shared Arrangements, Negotiated Terms','What are some communities in which you enjoy the shared arrangements and negotiated terms? Decide which ones you freely join and agree with, opt out of when the situation allows, or remain undecided about.',`<div class="contract-pile">${DESIGN['community-contract-scrolls'].entries.map((s,i)=>`<button class="contract-roll" data-new="contract" data-id="${s.key}" style="--offset:${[0,24,-22,10,34,-12,19,-26,4][i]}px" aria-label="Open ${esc(data.contracts[s.key]?.fields.Name||'Contract '+s.key)}">${asset('current/scroll-closed')}<span>${esc(data.contracts[s.key]?.fields.Name||'Contract '+s.key)}</span></button>`).join('')}</div><p class="note-hint">Choose a scroll to unroll its contract.</p><div class="btnrow">${btn('community-continue','Continue')}${btn('community-continue','Skip this','note-act')}${btn('keep-contracts','Stop and keep what I have','note-act')}</div>`);}
  function contract(id){activeContract=id;const draft=structuredClone(data.contracts[id]||{fields:{},ratings:{}});const labels=DESIGN['community-feeling-sliders'].labels;
    openModal('contract-dialog','Contract',`<p class="contract-subtitle">The arrangements I choose, question,<br>or leave undecided.</p>${DESIGN['community-contract-scrolls'].fields.map((label,i)=>field(label+':',draft.fields[label],label,['Community, group, or shared setting…','How much is expected, and how freely chosen?','The terms and responsibilities as they stand…','What I willingly stand behind…','What I would change, negotiate, or leave open…'][i])).join('')}<h3 class="serif">In this community, I feel:</h3><div class="feeling-sliders">${labels.map((label,i)=>`<div class="feeling-column"><div class="face-slider" role="slider" tabindex="0" aria-label="${label}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${draft.ratings[label]??50}" aria-valuetext="${draft.ratings[label]==null?'Unanswered':draft.ratings[label]+' out of 100'}" data-rating="${label}"><span class="slider-rail"></span><span class="slider-face">${[0,1,2,3,4].map(n=>asset('current/face-'+n,'face-stage stage-'+n)).join('')}</span></div><span class="feeling-label">${label}</span><output>${draft.ratings[label]==null?'Not set':Math.round(draft.ratings[label])}</output></div>`).join('')}</div><p class="note-hint">Leave any slider unanswered. Drag a face upward or downward, or use arrow keys, Home, and End.</p>`,values=>{draft.fields=values;if(!commit('contracts',id,draft))return false;redraw(contracts);returnFocus=view().querySelector(`[data-new="contract"][data-id="${id}"]`);notify('Contract kept.');});
    modal.querySelectorAll('.face-slider').forEach(slider=>{
      const label=slider.dataset.rating,face=slider.querySelector('.slider-face'),output=slider.parentElement.querySelector('output');let dragging=false;
      const paint=()=>{const value=draft.ratings[label]??50;face.style.bottom=value+'%';const k=value/25;slider.querySelectorAll('.face-stage').forEach((el,i)=>el.style.opacity=Math.max(0,1-Math.abs(k-i)));slider.setAttribute('aria-valuenow',Math.round(value));slider.setAttribute('aria-valuetext',draft.ratings[label]==null?'Unanswered':Math.round(value)+' out of 100');output.textContent=draft.ratings[label]==null?'Not set':Math.round(value);};
      const set=value=>{draft.ratings[label]=Math.max(0,Math.min(100,value));paint();};
      const at=e=>{const r=slider.getBoundingClientRect();set((r.bottom-e.clientY)/r.height*100);};
      slider.addEventListener('pointerdown',e=>{e.preventDefault();dragging=true;slider.setPointerCapture(e.pointerId);slider.focus({preventScroll:true});at(e);});
      slider.addEventListener('pointermove',e=>{if(dragging){e.preventDefault();at(e);}});slider.addEventListener('pointerup',()=>dragging=false);slider.addEventListener('pointercancel',()=>dragging=false);
      slider.addEventListener('keydown',e=>{const v=draft.ratings[label]??50;const vals={ArrowUp:v+1,ArrowRight:v+1,ArrowDown:v-1,ArrowLeft:v-1,PageUp:v+10,PageDown:v-10,Home:0,End:100};if(e.key in vals){e.preventDefault();set(vals[e.key]);}});paint();
    });
  }
  function attachmentPicker(){const items=[...NOTES.all().map(n=>({id:n.id,type:'note',label:NOTES.itemsOf(n).filter(i=>i.kind==='text').map(i=>i.text).join(' ').slice(0,120)||'A kept note'})),...ENGINE.lsGet(ENGINE.LS.marker,[]).map(m=>({id:m.id,type:'marker',label:m.label||'A kept marker'}))];openModal('language-dialog','Bring an existing note or marker',items.length?items.map(m=>`<label class="attachment-choice"><input type="checkbox" name="${esc(m.id)}" ${data.attachments.some(a=>a.id===m.id)?'checked':''}>${esc(m.label)}</label>`).join(''):'<p>No kept notes or markers yet. You can make a note from the notebook.</p>',v=>{const next=structuredClone(data);next.attachments=items.filter(m=>v[m.id]);if(!save(next))return false;redraw(gems);});}
  function collection(){page('kept-explorations','notebook','Things I’m keeping','Revisit your illustrated explorations and the arrangements you have made.',`<div class="kept-exploration-links">${[['garden','Growing self'],['spaces','Spaces for my self'],['gems','Aspects of my self'],['story-shelf','Inherited stories'],['influences','Influences'],['contracts','Community contracts']].map(([a,l])=>btn(a,l,'btn2')).join('')}</div><h2 class="h3">Arrangements and practices</h2><div class="options">${ENGINE.lsGet(ENGINE.LS.arrangement,[]).map(a=>btn('arrangement',esc(a.title||a.whatMatters||a.care||a.kind),'btn2',`data-id="${esc(a.id)}"`)).join('')||'<p class="muted">No arrangements kept yet.</p>'}</div>`);}
  function saveCollection(kind){let sections=[];let title='';if(kind==='gems'){title='Aspects of my self';sections=Object.values(data.gems).map(x=>({label:x.aspect,value:x.draws||x.aspect}));}if(kind==='spaces'){title='Spaces for my self';sections=Object.values(data.spaces).map((x,i)=>({label:'Space '+(i+1),value:x.words}));}if(kind==='garden'){title='The self I want to grow';sections=Object.values(data.garden).map(x=>({label:DESIGN['growth-categories'].categories.find(c=>c.key===x.category)?.label||'Growing',value:x.words}));}if(kind==='contracts'){title='My community contracts';sections=Object.values(data.contracts).flatMap(x=>Object.entries(x.fields).filter(([,v])=>v.trim()).map(([label,value])=>({label:(x.fields.Name||'Community')+' · '+label,value})));}if(!sections.length){notify('You can keep a few words first, or leave this open.');return;}ROOM.keepExploration(title,sections,'story',kind==='gems'?data.attachments.map(a=>({type:a.type,id:a.id})):[]);}
  const routes={garden,spaces,gems,story,influences,contracts,'story-shelf':shelf,collection};
  function enhance(){
    const home=view().querySelector('[data-od-id="home"]'),longer=view().querySelector('[data-od-id="longer-explorations"]');
    if(home){const pairs=[['.pv-plant','plant'],['.pv-torch','torch'],['.pv-magnet','magnet'],['.pv-book','book'],['.pv-pair','coffee-cups'],['.pv-circle','table'],['.pv-gift','gift'],['.o-plant .spot-art','plant'],['.o-torch .spot-art','torch'],['.o-magnet .spot-art','magnet'],['.o-book .spot-art','book'],['.o-pair .spot-art','coffee-cups'],['.o-circle .spot-art','table'],['.o-gift .spot-art','gift']];for(const [selector,name]of pairs){const el=view().querySelector(selector);if(el&&!el.dataset.updated){el.dataset.updated='true';el.innerHTML=name==='plant'?ROOM_LAYOUT.plantArt():asset('current/'+({book:'story-room','coffee-cups':'cups'}[name]||name));el.classList.add('current-miniature');if(name==='torch')el.classList.add('upward-torch');}}}
    if(longer)ROOM_LAYOUT.enhance(longer);
    const notes=view().querySelector('#notes-kept');if(notes&&!view().querySelector('[data-new="collection"]'))notes.insertAdjacentHTML('beforebegin',`<div class="btnrow">${btn('collection','Revisit my explorations and arrangements','btn2')}</div>`);
  }
  function refresh(){const id=view().querySelector('[data-page]')?.dataset.page;const map={'garden':garden,'spaces':spaces,'gems':gems,'story-book':story,'story-shelf':shelf,'influences':influences,'contracts':contracts,'kept-explorations':collection};if(map[id])redraw(map[id]);if(view().querySelector('[data-od-id=longer-explorations]'))redraw(UI.renderLongerExplorations);enhance();}
  function init(){
    document.addEventListener('keydown',e=>{if(e.key==='Escape')cancelActiveDrag?.();});
    window.addEventListener('finding-self-navigation',()=>cancelActiveDrag?.());
    const overrides={'open-practice':'garden','open-lamp-room':'spaces','open-explore':'gems','open-story':'story','open-influence':'influences','open-belonging':'contracts'};
    document.addEventListener('click',e=>{
      const el=e.target.closest('button');if(!el)return;
      if(el.dataset.suppressClick){e.preventDefault();e.stopImmediatePropagation();return;}
      if(pendingStoryReview&&['s-keep-own','s-keep-with'].includes(el.dataset.ract)){if(!keepStories()){e.preventDefault();e.stopImmediatePropagation();return;}pendingStoryReview=false;}
      const route=overrides[el.dataset.ract];if(route){e.preventDefault();e.stopImmediatePropagation();routes[route]();return;}
      if(el.dataset.act==='export-data'){e.preventDefault();e.stopImmediatePropagation();const stores={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k.startsWith('fsaw.')||k.startsWith('fsaw-'))stores[k]=localStorage.getItem(k);}const url=URL.createObjectURL(new Blob([JSON.stringify({format:'finding-self-backup',version:1,exportedAt:new Date().toISOString(),stores},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='finding-self-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);notify('Your backup includes notes, explorations, and scenarios.');return;}
      if(el.dataset.act==='delete-data'){e.preventDefault();e.stopImmediatePropagation();if(!confirm('Delete all Finding Self data saved in this browser? This cannot be undone. Export a backup first if you want to keep it.'))return;const keys=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k.startsWith('fsaw.')||k.startsWith('fsaw-'))keys.push(k);}keys.forEach(k=>localStorage.removeItem(k));data=empty();storyDraft=null;influenceDraft=null;window.location.reload();return;}
      if(el.dataset.ract==='open-contrib'){e.preventDefault();e.stopImmediatePropagation();ITERATION.contributions();return;}const a=el.dataset.new;if(!a)return;e.preventDefault();e.stopImmediatePropagation();const id=el.dataset.id;
      if(routes[a]){routes[a]();if(a==='story-shelf'){window.scrollTo(0,shelfScroll);view().querySelector(`[data-new="story-open"][data-id="${storyIndex}"]`)?.focus({preventScroll:true});}return;}
      const actions={
        appearance,'appearance-choice':()=>{const next=structuredClone(data);next.appearance=id;if(save(next)){closeModal();redraw(spaces);view().querySelector('[data-new="appearance"]')?.focus();}},'close-modal':closeModal,exit:()=>NAV.exit(),space:()=>editSpace(id),gem:()=>editGem(id),contract:()=>contract(id),arrangement:()=>ROOM.openArrangement(id),
        'story-open':()=>{shelfScroll=window.scrollY;storyIndex=Number(id);story();},'story-prev':()=>{storyIndex--;redraw(story);},'story-next':()=>{storyIndex++;redraw(story);},'story-add':()=>{ensureStories();storyDraft.push(blankStory());storyIndex=storyDraft.length-1;redraw(story);},
        bookmark:()=>{storyDraft[storyIndex].bookmark=el.dataset.value;redraw(story);},'bookmark-remove':()=>{storyDraft[storyIndex].bookmark=null;redraw(story);},'story-save':keepStories,'story-review':()=>{pendingStoryReview=true;ROOM.reviewStories(storyDraft);},
        'garden-category':()=>{selectedCategory=DESIGN['growth-categories'].categories.find(c=>c.key===id);redraw(garden);},'garden-slot':()=>editLeaf(id),'garden-language':()=>languagePicker(id),
        'language-pick':()=>{modal.querySelector('[name="words"]').value=el.dataset.value;modal.querySelector('[name="words"]').focus();},
        'growth-continue':()=>ROOM.continueGrowth(Object.values(data.garden).map(x=>x.words).join('\n')),
        'community-continue':()=>ROOM.continueCommunity(data.contracts[activeContract]||{fields:{}}),
        'influence-continue':()=>ROOM.continueInfluence(Object.values(influenceDraft||{}).filter(x=>x.trim()).join('\n')),
        'influence-save':()=>{const next=structuredClone(data);next.influences=structuredClone(influenceDraft);if(save(next))notify('Your influences are kept.');},
        'keep-garden':()=>saveCollection('garden'),'keep-spaces':()=>saveCollection('spaces'),'keep-gems':()=>saveCollection('gems'),'keep-contracts':()=>saveCollection('contracts'),
        'gem-attach':attachmentPicker,'gem-detach':()=>{const next=structuredClone(data);next.attachments=next.attachments.filter(a=>a.id!==id);if(save(next))redraw(gems);}
      };actions[a]?.();
    },true);
    new MutationObserver(enhance).observe(view(),{childList:true,subtree:true});enhance();
  }
  return {init,refresh,notify,intersects,gemLit,page,openModal,closeModal,commit,save,asset,btn,field,esc,redraw,routes,dragTo,seenGrowth(){if(!data.growthIntroSeen){const next=structuredClone(data);next.growthIntroSeen=true;save(next);}},get data(){return structuredClone(data);}};
})();
