/* September 23 design decisions, composed with the existing exploration engine. */
'use strict';
window.ITERATION=(()=>{
  const $=s=>document.querySelector(s),E=()=>EXPLORATIONS;
  const roomAbout='Each item in the room is a tool we made that you could use to explore yourself or just play around with. We hope you’ll find a few of them that you especially like :) Our concept behind this room was that our self is made of many different aspects, and that we can explore and better serve each aspect of ourselves in different ways.';
  const plantAbout='This exploration was primarily made for those who want more room for certain parts of themselves to grow. Pick particular relationships to people, places, interests, feelings, experiences, memories, activities, personality traits, etc. that feel like ‘you’. Note them down and see where your writing goes.';
  const normalize=s=>s.replace(/[‘’]/g,"'").replace(/[“”]/g,'"').replace(/\s+/g,' ').trim();
  function dialog(title,body){const focus=document.activeElement,d=document.createElement('dialog');d.className='illustrated-dialog plain-dialog';d.setAttribute('aria-label',title);d.innerHTML=`<div class="dialog-surface"><h2>${E().esc(title)}</h2>${body}<div class="btnrow"><button class="btn2" data-dismiss>Close</button></div></div>`;document.body.append(d);d.showModal();const close=()=>{d.close();d.remove();if(focus?.isConnected)focus.focus();};d.addEventListener('cancel',e=>{e.preventDefault();close();});d.addEventListener('click',e=>{if(e.target===d||e.target.closest('[data-dismiss]'))close();});return {node:d,close};}
  function aboutButton(target,text){const label='About this exploration';if(!target||target.parentElement.querySelector('.about-control'))return;const b=document.createElement('button');b.type='button';b.className='btn2 about-control';b.textContent=label;b.onclick=()=>dialog(label,text.split(/\n\s*\n/).map(paragraph=>`<p>${E().esc(paragraph)}</p>`).join(''));target.after(b);}
  function contributions(){E().page('contributions','contribution','Ways I Want to Contribute','Open an object. Imagine what you’d enjoy contributing.',`<div class="contribution-objects">${ITERATION_DATA.contributions.map(item=>{const b=item.key==='notebook'?[49,64,110,64]:item.box,w=item.key==='others'?428:204,h=item.key==='others'?100:180;return `<button class="contribution-object ${item.key==='others'?'wide':''}" data-iteration="contribution" data-id="${item.key}" aria-label="${E().esc(item.label)}"><span class="contribution-art">${E().asset('current/contribution-'+item.key)}<span class="contribution-preview ${E().data.contributions[item.key]?'has-words':''}" style="left:${b[0]/w*100}%;top:${b[1]/h*100}%;width:${b[2]/w*100}%;height:${b[3]/h*100}%">${E().esc(E().data.contributions[item.key]||item.cue)}</span></span><span class="contribution-label">${E().esc(item.label)}</span></button>`;}).join('')}</div><p class="note-hint" id="contribution-status">One object is enough. You can return and change your words.</p><button class="btn" data-iteration="keep-contributions">Keep these contributions</button>`);enhance();}
  function editContribution(id){const item=ITERATION_DATA.contributions.find(x=>x.key===id);if(!item)return;E().openModal('contribution-dialog',E().esc(item.label),`<p>What would your own version look like? A few words, a wish, or an unfinished thought.</p>${E().field('My words',E().data.contributions[id]||'','words','Jot down a thought…')}`,v=>{if(!E().commit('contributions',id,v.words))return false;E().closeModal();E().redraw(contributions);$(`[data-iteration="contribution"][data-id="${id}"]`)?.focus();E().notify('Your words are kept on this device.');});}
  function enhance(){const card=$('#view .card');if(!card)return;const id=card.dataset.page||card.dataset.odId;
    const major={garden:plantAbout, 'longer-explorations':roomAbout};
    let intro=card.querySelector('.support');
    if(major[id]){if(id==='longer-explorations'&&intro)intro.textContent='Choose an object to explore, or simply look around.';aboutButton(intro,major[id]);}
    else {
      const frames={spaces:'14:666',gems:'14:810','story-shelf':'14:959','story-book':'122:575',influences:'122:595',contracts:'122:395',contributions:'122:495','exploration-archive':'379:2161','room-proposal':'122:475','room-small-keep':'122:675','room-return':'122:775','room-gather':'122:795','room-review':'122:735','room-review-after':'122:755','room-gather-p':'122:833','room-gather-r':'122:853','room-cue':'122:873','room-notice':'122:933'};
      const legacyFrame=card.querySelector('#room-q2')?'14:487':card.querySelector('#room-q4')?'125:991':card.querySelector('#room-b3a')?'122:435':card.querySelector('#room-sf-opens')?'122:615':card.querySelector('#room-sf-share')?'122:655':id==='room-small'&&/repair/i.test(card.querySelector('h1,h2')?.textContent||'')&&card.querySelector('#room-s1')?'125:1071':null;const item=ITERATION_DATA.introductions.find(x=>x.frame===(legacyFrame||frames[id]))||ITERATION_DATA.introductions.find(x=>[...card.querySelectorAll('.support,p')].some(p=>normalize(p.textContent)===normalize(x.original)));
      if(item){if(!frames[id]&&!legacyFrame)intro=[...card.querySelectorAll('.support,p')].find(p=>normalize(p.textContent)===normalize(item.original));if(intro){intro.textContent=item.summary;aboutButton(intro,item.original+(item.frame==='122:595'?"\n\n*the background objects on this page are just for inspiration - what you write doesn't have to match them":''));}}
    }
    card.querySelectorAll('.relationship-art img').forEach(img=>{const key=img.src.match(/relationships-(\w+)\.svg/)?.[1];if(key)img.src=`assets/current/relationship-${key}.svg`;});
    if(id==='influences'&&!card.dataset.currentArt){card.dataset.currentArt='true';const geometry={book:[[22.2,63.61,68.66,65.63],[118.13,63.61,68.66,65.63]],music:[[40,107,103,36]],sport:[[64.61,78.75,82.78,51.48]],place:[[118,84.22,80,56]],person:[[56,153.44,96,30]],mentor:[[48.45,56.53,110.05,53.5]]};card.querySelectorAll('.influence-object').forEach((el,i)=>{const key=DESIGN['influence-writing-objects'].items[i].key;el.dataset.kind=key;el.querySelectorAll('textarea').forEach((t,j)=>{const [x,y,w,h]=geometry[key][j];t.style.cssText=`left:${x/2.08}%;top:${y/1.85786}%;width:${w/2.08}%;height:${h/1.85786}%`;});});}
    if(id==='settings'&&!card.querySelector('[data-helper="choose"]')){card.insertAdjacentHTML('beforeend','<section class="helper-settings"><h2>AI helper</h2><p>Choose among three placeholder helpers. You decide what a helper can use.</p><button class="btn2" data-helper="choose">Choose AI helper</button> <button class="note-act" data-helper="off">Turn off AI helper</button></section>');}
    // The supplied notebook has two independently operable page controls.
    const book=card.querySelector('.book-shape');if(book&&!book.dataset.currentArt){book.dataset.currentArt='true';book.classList.add('current-notebook');}
    window.HELPER?.enhance();
  }
  function init(){document.addEventListener('click',e=>{const b=e.target.closest('[data-iteration]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(b.dataset.iteration==='contribution')editContribution(b.dataset.id);if(b.dataset.iteration==='keep-contributions'){if(E().save(E().data)){const n=$('#contribution-status');if(n)n.textContent='Kept. You can return whenever you like.';E().notify('Kept. You can return whenever you like.');}}},true);new MutationObserver(enhance).observe($('#view'),{childList:true});new MutationObserver(()=>{const d=$('dialog.contract-dialog .dialog-surface');if(d&&!d.querySelector('.scroll-art')){d.insertAdjacentHTML('afterbegin','<div class="scroll-art" aria-hidden="true"><div class="scroll-top"><img src="assets/current/scroll-top.svg" alt=""></div><div class="scroll-middle"><img src="assets/current/scroll-middle.svg" alt=""></div><div class="scroll-bottom"><img src="assets/current/scroll-bottom.svg" alt=""></div></div>');}}).observe(document.body,{childList:true});enhance();}
  return {init,enhance,contributions,dialog,aboutButton};
})();
