/* Session-only presence and explicit, request-scoped helper workspace.
   Placeholder passports deliberately cannot submit a model request. */
'use strict';
window.HELPER=(()=>{
  const E=()=>EXPLORATIONS,$=s=>document.querySelector(s),esc=x=>E().esc(x);
  let enabled=false,selected=null,visible=false,token=0,timer=null,bypass=false,pending=false,workspace=null,origin=null,host=null,step='select',chosen=new Set(),operation='',instruction='',pieces=[],dirty=false,controller=null,models=new Map();
  const operations=['Help me find words','Suggest possible connections','Help me sort these pieces','Offer another way to look'];
  const helperName=id=>'Helper '+id;
  function off(){enabled=false;visible=false;token++;clearTimeout(timer);$('.helper-companion')?.remove();E().notify('AI helper is off.');}
  function arrival(){token++;const t=token;clearTimeout(timer);visible=false;$('.helper-companion')?.remove();if(!enabled||workspace)return;timer=setTimeout(()=>{if(t!==token||!enabled||workspace)return;visible=true;enhance(true);},3000);}
  function guard(fn){if(!enabled||bypass){fn();return;}if(pending)return;pending=true;const focus=document.activeElement;const d=ITERATION.dialog('do you still want AI bot to follow you here?','<div class="btnrow"><button class="btn" data-follow="yes">Yes</button><button class="btn2" data-follow="no">No</button><button class="note-act" data-follow="stay">Stay on this page</button></div>');d.node.querySelector('[data-dismiss]').parentElement.remove();const cancel=()=>{pending=false;};d.node.addEventListener('close',cancel);d.node.addEventListener('cancel',cancel);d.node.addEventListener('click',e=>{const a=e.target.closest('[data-follow]')?.dataset.follow;if(!a){if(e.target===d.node)pending=false;return;}pending=false;d.close();if(a==='stay'){focus?.focus();return;}if(a==='no')off();bypass=true;try{fn();}finally{bypass=false;}if(enabled)arrival();});}
  function enhance(animate=false){const card=$('#view .card');if(!card||workspace)return;if(enabled&&visible&&!card.querySelector('.helper-companion')){card.insertAdjacentHTML('beforeend',`<button class="helper-companion ${animate?'arriving':''}" data-helper="menu">${E().asset('current/helper')}<span>${helperName(selected)}<br>AI helper</span></button>`);}if(!enabled)card.querySelector('.helper-companion')?.remove();const context=card.dataset.page||card.dataset.odId;const saved=E().data.aiAdditions?.[context]||[];if(saved.length&&!card.querySelector('.helper-saved'))card.insertAdjacentHTML('beforeend',`<section class="helper-saved"><h2 class="h3">Kept pieces</h2>${saved.map((p,i)=>`<p>${esc(p.text)}</p><small class="helper-provenance">AI-origin · ${esc(p.helperName||'Helper')}</small><div><button class="note-act" data-helper="edit-saved" data-id="${i}">Edit</button><button class="note-act" data-helper="remove-saved" data-id="${i}">Remove</button></div>`).join('')}</section>`);}
  function page(id,title,support,body){NAV.withoutHistory(()=>E().page('helper-'+id,'helper',title,support,body));}
  function choose(){if(!origin)origin=NAV.origin();workspace='chooser';visible=false;clearTimeout(timer);chooser();}
  function chooser(){workspace='chooser';page('choose','Choose your AI helper','Meet three helpers. Choose one to use, or take a look at its passport.',`<p class="note-hint">Three placeholder helpers · model details to be added</p><div class="helper-cards">${[1,2,3].map(id=>`<button class="helper-card" data-helper="inspect" data-id="${id}">${E().asset('current/helper')}<span><b>${helperName(id)}</b>Placeholder model ${id}<br>Tap to choose or view passport</span></button>`).join('')}</div><p class="note-hint">${selected?helperName(selected):'No helper selected'}</p>`);}
  function inspect(id){const d=ITERATION.dialog(helperName(id),`<p>Placeholder model ${id}</p><div class="btnrow"><button class="btn" data-use-helper="${id}">use this AI helper</button><button class="btn2" data-passport="${id}">view this AI helper's passport</button></div>`);d.node.addEventListener('click',e=>{const use=e.target.closest('[data-use-helper]'),pass=e.target.closest('[data-passport]');if(use){selected=id;enabled=true;d.close();returnOrigin(false);}else if(pass){d.close();passport(id);}});}
  function passport(id){workspace='passport';const m=models.get(String(id));page('passport-'+id,helperName(id)+' · Passport','Model and data-handling details',`<dl>${[['Helper identity',helperName(id)],['Model',m?.passport.model||'Placeholder model '+id],['Provider',m?.passport.provider||'Not configured'],['Version / release',m?.passport.version||'Not specified'],['Processing location',m?.passport.location||'Not specified'],['Retention period',m?.passport.retention||'Not specified'],['Training policy',m?.passport.training||'Not specified']].map(([k,v])=>`<dt><b>${k}</b></dt><dd>${esc(v)}</dd>`).join('')}</dl><p>Live requests are unavailable until a real model and its passport details are configured.</p><button class="btn2" data-helper="chooser">Return to chooser</button>`);}
  function returnOrigin(ask=true){const perform=()=>{controller?.abort();controller=null;workspace=null;const p=origin;origin=null;NAV.restoreBookmark(p);if(enabled)arrival();};if(dirty){const d=ITERATION.dialog('Leave the helper?','<p>Your working pieces have not been kept.</p><button class="btn2" data-leave-helper>Leave without keeping</button>');d.node.querySelector('[data-leave-helper]').onclick=()=>{dirty=false;d.close();ask?guard(perform):perform();};return;}ask?guard(perform):perform();}
  function entries(){const d=E().data,key=host?.key;let list=[];const push=(id,text)=>{if(text?.trim())list.push({id:String(id),text});};if(key==='garden')Object.entries(d.garden).forEach(([id,x])=>push(id,x.words));else if(key==='spaces')Object.entries(d.spaces).forEach(([id,x])=>push(id,[x.name,x.words].filter(Boolean).join('\n')));else if(key==='gems')Object.entries(d.gems).forEach(([id,x])=>push(id,[x.aspect,x.draws].filter(Boolean).join('\n')));else if(/story/.test(key))d.stories.forEach(x=>push(x.id,[x.source,x.words].filter(Boolean).join('\n')));else if(key==='contracts')Object.entries(d.contracts).forEach(([id,x])=>push(id,Object.entries(x.fields).map(([k,v])=>k+': '+v).join('\n')));else if(key==='influences')Object.entries(d.influences).forEach(([id,x])=>push(id,x));else if(key==='contributions')Object.entries(d.contributions).forEach(([id,x])=>push(id,x));else{document.querySelectorAll('#view textarea').forEach((t,i)=>push(t.id||String(i),t.value));}return list;}
  let material=[];
  function start(){origin=NAV.bookmark();host={key:$('#view .card')?.dataset.page||$('#view .card')?.dataset.odId,title:$('#view h1')?.textContent||'Exploration'};material=entries();chosen=new Set();operation='';instruction='';pieces=[];dirty=false;workspace='task';clearTimeout(timer);visible=false;selection();}
  function badge(){return `<div class="helper-status"><b>${helperName(selected)}</b><p>${esc(host?.title||'')}</p></div>`;}
  function selection(){step='select';page('select','Choose what the helper can use','Select only the entries you want to work with.',badge()+`<div>${material.length?material.map(x=>`<label class="helper-material"><input type="checkbox" data-material="${esc(x.id)}" ${chosen.has(x.id)?'checked':''}><span><small>Your entry</small><br>${esc(x.text)}</span></label>`).join(''):'<p>No written entries here yet. Keep some words in this exploration first.</p>'}</div><p class="note-hint">Only included entries will be sent. You can review them before allowing this request.</p><button class="btn" data-helper="operations">Choose an operation</button>`);}
  function operationsPage(){if(!chosen.size){E().notify('Choose at least one entry.');return;}step='operation';page('operation','Choose an operation','What would you like to do with these pieces?',badge()+`<div class="room-options-list">${operations.map((op,i)=>`<button class="btn2" data-operation="${i}">${op}</button>`).join('')}</div><button class="note-act" data-helper="selection">Change selected material</button>`);}
  function review(){step='review';const model=models.get(String(selected));page('review','Review this request','Check the material and context before allowing access.',badge()+`<h2 class="h3">Requested operation</h2><p>${esc(operation)}</p><h2 class="h3">Included entries</h2>${material.filter(x=>chosen.has(x.id)).map(x=>`<blockquote>${esc(x.text)}</blockquote>`).join('')}${E().field('Optional instruction',instruction,'instruction','Ask for wording without interpretation, or add context…')}<p class="note-hint">Also included: this exploration title, your chosen operation, and instructions to offer tentative wording without diagnoses or claims about hidden motives. No other entries, pages or earlier helper requests are included. Permission applies to this request only.</p><p>${model?esc(model.passport.provider+' · '+model.passport.model+' · '+model.passport.version):'Placeholder model · live requests are unavailable until its passport is complete.'}</p><div class="btnrow"><button class="btn" data-helper="request" ${model?'':'disabled'}>Allow this request</button><button class="btn2" data-helper="operations">Change material or operation</button></div>`);$('[name=instruction]').oninput=e=>instruction=e.target.value;}
  async function request(){const config=models.get(String(selected));if(!config)return;const approved=material.filter(x=>chosen.has(x.id)).map(x=>({...x})),identity=String(selected);controller=new AbortController();const requestController=controller,signal=requestController.signal;step='processing';page('processing','Generating possible pieces','Working with the material you approved.',badge()+'<p role="status">Request in progress.</p><button class="btn2" data-helper="cancel-request">Cancel request</button>');const timeout=setTimeout(()=>requestController.abort(),45000);const cancelled=new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(new DOMException('Request stopped','AbortError')),{once:true}));try{const result=await Promise.race([config.generate({entries:approved,operation,instruction,exploration:host.title,helperId:identity,passport:clone(config.passport),guidance:'Offer tentative wording. Do not diagnose, infer hidden motives, or claim authority over the person. Use only the approved entries.'},signal),cancelled]);if(signal.aborted||!workspace||selected!==identity)return;const allowed=new Set(approved.map(x=>x.id));pieces=(Array.isArray(result)?result:[]).filter(p=>p&&typeof p.text==='string'&&p.text.trim()&&Array.isArray(p.sourceIds)&&p.sourceIds.length&&p.sourceIds.every(id=>allowed.has(String(id)))).slice(0,24).map(p=>({id:crypto.randomUUID(),text:p.text,sourceIds:p.sourceIds.map(String),selected:false,group:'',helperId:identity,helperName:helperName(identity),passport:clone(config.passport),operation}));if(!pieces.length){step='empty';page('empty','Nothing fits yet','No usable suggestions were returned.','<button class="btn2" data-helper="review">Review another request</button><button class="note-act" data-helper="return">Return to exploration</button>');}else{dirty=true;work();}}catch(err){if(!workspace)return;step='error';page('error',signal.aborted?'Request stopped':'No suggestions received','Your original entries are unchanged.','<button class="btn2" data-helper="review">Review and try again</button><button class="note-act" data-helper="return">Return to exploration</button>');}finally{clearTimeout(timeout);if(controller===requestController)controller=null;}}
  const clone=x=>structuredClone(x);
  function work(){step='work';page('work','Your working arrangement','Select, arrange, edit or leave the pieces. Nothing is kept until you choose.',badge()+`<div class="helper-workspace">${pieces.map((p,i)=>`<article class="helper-piece" data-piece="${p.id}" data-group="${p.group}"><button class="note-act piece-handle" aria-label="Drag this piece">Drag to rearrange</button><label><input type="checkbox" data-piece-selected="${p.id}" ${p.selected?'checked':''}> Include this piece</label><textarea aria-label="Piece ${i+1}" data-piece-text="${p.id}">${esc(p.text)}</textarea><small class="helper-provenance">AI-origin · sources: ${p.sourceIds.map(esc).join(', ')}${p.group?' · group '+esc(p.group):''}</small><div><button class="note-act" data-piece-action="up" data-id="${p.id}">Move up</button><button class="note-act" data-piece-action="down" data-id="${p.id}">Move down</button><button class="note-act" data-piece-action="ungroup" data-id="${p.id}">Ungroup</button><button class="note-act" data-piece-action="discard" data-id="${p.id}">Discard</button></div></article>`).join('')}</div><div class="btnrow"><button class="btn2" data-helper="group">Group selected</button><button class="btn2" data-helper="combine">Combine selected</button><button class="btn" data-helper="save-preview">Choose what to keep</button></div>`);document.querySelectorAll('[data-piece]').forEach(el=>E().dragTo(el.querySelector('.piece-handle'),'[data-piece]',target=>{const from=pieces.findIndex(p=>p.id===el.dataset.piece),to=pieces.findIndex(p=>p.id===target.dataset.piece);if(from===to)return;const [p]=pieces.splice(from,1);pieces.splice(to,0,p);dirty=true;work();}));}
  function savePreview(){const chosenPieces=pieces.filter(p=>p.selected);if(!chosenPieces.length){E().notify('Choose the pieces you want to keep.');return;}step='save';page('save','Choose what to keep','These additions stay alongside your original entries.',badge()+chosenPieces.map(p=>`<blockquote>${esc(p.text)}</blockquote>`).join('')+'<button class="btn" data-helper="save">Keep these pieces</button><button class="btn2" data-helper="work">Back to working arrangement</button>');}
  function save(){const next=E().data;next.aiAdditions||={};next.aiAdditions[host.key]||=[];for(const p of pieces.filter(x=>x.selected))if(!next.aiAdditions[host.key].some(x=>x.id===p.id))next.aiAdditions[host.key].push(clone(p));if(E().save(next)){dirty=false;E().notify('Kept with this exploration.');returnOrigin();}}
  function hostIntent(b){if(b.disabled||b.closest('dialog,[role=dialog]'))return false;if(b.dataset.nav)return true;if(b.dataset.helper)return false;if(b.dataset.roomOpen)return true;if(['basket','cupboard'].includes(b.dataset.roomId))return true;const a=b.dataset.new;if(a)return ['garden','spaces','gems','story','influences','contracts','story-shelf','story-open','collection','arrangement','exit','growth-continue','community-continue','influence-continue','keep-garden','keep-spaces','keep-gems','keep-contracts','story-review'].includes(a);const r=b.dataset.ract;if(r)return /^(open-|home$|back$|p-next|p-skip|p-stop|p-from-condition|notice-|n-save|n-back|b-next|b-skip|b-save-plain|b-to-proposal|b-back|prop-save|a-edit|a-save-edit|a-review|a-attach|a-cue|a-return|a-gather|r-save|ret-save|cue-|g-note|g-condition|g-practice|g-resource|g-add-|g-save-resource|g-open-practice|s-next|s-stop|s-back|s-keep-|pick-|room-from-note|connect-note|p-material-x|x-save)/.test(r);const act=b.dataset.act;if(act)return /^(home|longer-explorations|starters|starter-detail|start-starter|entry|onboarding|ob-back|ob-skip|back|exit|wrong|practice-start|marker-practice|sim-fire|inv-back|inv-cancel|inv-use|settings-exit|resume|custom-submit|multi-continue)$/.test(act);if(b.dataset.nact)return /^(open|new|back|save|keep|edit|discard-yes)/.test(b.dataset.nact);if(b.dataset.scact)return /^(open|new|back|template|copy|blank|run)/.test(b.dataset.scact);return b.hasAttribute('data-opt')||b.hasAttribute('data-ob-a')||b.hasAttribute('data-inv-pick')||b.dataset.ui==='settings';}
  function init(){window.addEventListener('keydown',e=>{if(e.key==='Escape'&&enabled&&!workspace&&NAV.debug.settings&&!document.querySelector('dialog[open]')){e.preventDefault();e.stopImmediatePropagation();guard(()=>NAV.exit());}},true);window.addEventListener('finding-self-navigation',()=>{if(!workspace&&enabled)arrival();});window.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(workspace&&b.dataset.nav){e.preventDefault();e.stopImmediatePropagation();if(workspace==='passport')chooser();else if(workspace==='chooser')returnOrigin();else if(b.dataset.nav==='exit')returnOrigin();else ({select:returnOrigin,operation:selection,review:operationsPage,work:review,save:work,processing:()=>controller?.abort(),error:review,empty:review})[step]?.();return;}if(enabled&&!bypass&&!workspace&&hostIntent(b)){if(window.NOTES?.navigationBusy?.()){E().notify('Stop or cancel the recording before leaving this note.');e.preventDefault();e.stopImmediatePropagation();return;}e.preventDefault();e.stopImmediatePropagation();guard(()=>b.click());}},true);
    document.addEventListener('change',e=>{const t=e.target;if(t.dataset.material){t.checked?chosen.add(t.dataset.material):chosen.delete(t.dataset.material);}if(t.dataset.pieceSelected){pieces.find(p=>p.id===t.dataset.pieceSelected).selected=t.checked;}},true);
    document.addEventListener('input',e=>{if(e.target.dataset.pieceText){pieces.find(p=>p.id===e.target.dataset.pieceText).text=e.target.value;dirty=true;}},true);
    document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const a=b.dataset.helper;if(a){e.preventDefault();e.stopImmediatePropagation();if(a==='start'||a==='off'){const modal=b.closest('dialog');modal?.close();modal?.remove();}const actions={choose,chooser,inspect:()=>inspect(b.dataset.id),off,menu:()=>{const d=ITERATION.dialog(helperName(selected),'<div class="btnrow"><button class="btn" data-helper="start">AI helper</button><button class="note-act" data-helper="off">Turn off AI helper</button></div>');d.node.addEventListener('click',ev=>{if(ev.target.closest('[data-helper]'))d.close();});},start,selection,operations:operationsPage,review,request,'cancel-request':()=>controller?.abort(),work,'save-preview':savePreview,save,return:returnOrigin,group:()=>{const id=String(Date.now()).slice(-4);pieces.filter(p=>p.selected).forEach(p=>p.group=id);dirty=true;work();},combine:()=>{const selectedPieces=pieces.filter(p=>p.selected);if(selectedPieces.length<2){E().notify('Choose at least two pieces to combine.');return;}const merged={...selectedPieces[0],id:crypto.randomUUID(),text:selectedPieces.map(p=>p.text).join('\n\n'),sourceIds:[...new Set(selectedPieces.flatMap(p=>p.sourceIds))],group:''};pieces=pieces.filter(p=>!p.selected);pieces.push(merged);dirty=true;work();},'edit-saved':()=>editSaved(Number(b.dataset.id)),'remove-saved':()=>removeSaved(Number(b.dataset.id))};actions[a]?.();}if(b.dataset.operation!==undefined){operation=operations[Number(b.dataset.operation)];review();}if(b.dataset.pieceAction){const i=pieces.findIndex(p=>p.id===b.dataset.id),a=b.dataset.pieceAction;if(a==='discard')pieces.splice(i,1);else if(a==='ungroup')pieces[i].group='';else{const j=clamp(i+(a==='up'?-1:1),0,pieces.length-1);[pieces[i],pieces[j]]=[pieces[j],pieces[i]];}dirty=true;work();}},true);
  }
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  function savedKey(){return $('#view .card')?.dataset.page||$('#view .card')?.dataset.odId;}
  function editSaved(i){const key=savedKey(),p=E().data.aiAdditions[key][i];E().openModal('contribution-dialog','Make the words yours',E().field('Words',p.text,'words'),v=>{const next=E().data;next.aiAdditions[key][i].text=v.words;if(!E().save(next))return false;$('.helper-saved')?.remove();enhance();});}
  function removeSaved(i){const key=savedKey(),next=E().data;next.aiAdditions[key].splice(i,1);if(E().save(next)){$('.helper-saved')?.remove();enhance();}}
  function configure(id,passport,generate){if(!['model','provider','version','location','retention','training'].every(k=>typeof passport[k]==='string'&&passport[k].trim())||typeof generate!=='function')throw Error('Complete model passport and request adapter required.');models.set(String(id),{passport:clone(passport),generate});}
  return {init,enhance,guard,configure,get debug(){return {enabled,selected,visible,workspace,step,pending};}};
})();
