const {chromium}=require('C:/Users/hurri/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{
 const b=await chromium.launch({headless:true,channel:'msedge'});const p=await b.newPage({viewport:{width:1000,height:1100}});const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://127.0.0.1:4173/app/index.html');await p.locator('[data-act="longer-explorations"]').waitFor();
 async function exit(){await p.locator('[data-nav="exit"]').click();}
 async function drag(source,target){const a=await source.boundingBox(),z=await target.boundingBox();await p.mouse.move(a.x+a.width/2,a.y+a.height/2);await p.mouse.down();await p.mouse.move(z.x+z.width/2,z.y+z.height/2,{steps:15});await p.mouse.up();}
 await p.locator('[data-act="longer-explorations"]').click();await p.locator('[data-ract="open-explore"]').click();
 await p.locator('.gem-target').first().click({force:true});assert.equal(await p.locator('dialog').count(),0,'Unlit gem does not open');
 const handle=p.locator('.movable-torch');await handle.scrollIntoViewIfNeeded();const h=await handle.boundingBox();await p.mouse.move(h.x+h.width/2,h.y+h.height/2);await p.mouse.down();await p.mouse.move(h.x+h.width/2-90,h.y+h.height/2-60,{steps:15});await p.mouse.up();
 let lit=p.locator('.gem-target.lit');assert.ok(await lit.count()>0,'Free drag illuminates a target');const gid=await lit.first().getAttribute('data-id');await lit.first().click();await p.locator('[name="aspect"]').fill('My curiosity');await p.locator('[name="draws"]').fill('Making things without an outcome');await p.locator('dialog button[type="submit"]').click();assert.equal(await p.evaluate(id=>EXPLORATIONS.data.gems[id].aspect,gid),'My curiosity');await exit();
 await p.locator('[data-ract="open-practice"]').click();const pile=p.locator('[data-new="garden-category"][data-id="feelings"]'),leaf=p.locator('[data-new="garden-slot"][data-id="2"]');await pile.scrollIntoViewIfNeeded();await drag(pile,leaf);await p.locator('dialog').waitFor();await p.locator('[name="words"]').fill('A little more ease');await p.locator('dialog button[type="submit"]').click();assert.equal(await p.evaluate(()=>EXPLORATIONS.data.garden['2'].category),'feelings');await exit();
 await p.locator('[data-ract="open-story"]').click();await p.locator('[name="words"]').fill('My own pace matters');await drag(p.locator('[data-new="bookmark"][data-value="Keep"]'),p.locator('[data-book-drop]'));assert.equal(await p.locator('[data-new="bookmark"][data-value="Keep"]').getAttribute('aria-pressed'),'true');const count=await p.evaluate(()=>NAV.debug.history.length);for(let i=0;i<5;i++)await p.locator('[data-new="story-add"]').click();assert.ok((await p.locator('.story-pages').innerText()).includes('8 of 8'));assert.equal(await p.evaluate(()=>NAV.debug.history.length),count);await exit();
 await p.locator('[data-ract="open-belonging"] span').click();await p.locator('[data-new="contract"][data-id="3"]').click();const s=p.locator('[role="slider"]').nth(1);await p.waitForTimeout(300);await s.scrollIntoViewIfNeeded();const box=await s.boundingBox();await p.mouse.move(box.x+18,box.y+box.height/2);await p.mouse.down();await p.mouse.move(box.x+18,box.y+box.height*.2,{steps:8});await p.mouse.up();const value=Number(await s.getAttribute('aria-valuenow'));assert.ok(value>=78&&value<=82);await p.locator('[name="Name"]').fill('A group with a little energy');await p.locator('dialog button[type="submit"]').click();assert.ok((await p.evaluate(()=>EXPLORATIONS.data.contracts['3'].ratings.Energized))>78);await exit();await exit();
 // Existing notebook: real editable words, photo upload, save, and reload.
 await p.locator('[data-nact="open-composer"]').click();await p.locator('[data-nact="sc-text"]').click();const words=p.locator('[contenteditable="true"]');await words.fill('Something I noticed today');await words.press('Tab');await p.locator('#note-photo-input').setInputFiles(__dirname+'/photo-fixture.png');await p.waitForTimeout(250);await p.locator('[data-nact="keep"]').click();assert.equal(await p.evaluate(()=>NOTES.all().length),1);assert.equal(await p.evaluate(()=>NOTES.itemsOf(NOTES.all()[0]).some(i=>i.kind==='photo')),true);await exit();await exit();
 // Each seeded check-in routes and restores its prior question with Back.
 for(const starter of ['SS01','SS02','SS06']){await p.locator(`[data-starter="${starter}"][data-act="start-starter"]`).click();const node=await p.evaluate(()=>ENGINE.Session.currentNodeId);await p.locator('[data-opt]:not(.custom):not(.more)').first().click();if(await p.evaluate(()=>ENGINE.Session.currentNodeId)===node && await p.locator('[data-opt].continue').count())await p.locator('[data-opt].continue').click();await p.locator('[data-nav="back"]').click();assert.equal(await p.evaluate(()=>ENGINE.Session.currentNodeId),node);await exit();}
 // Scenario editor and nested Exit return to its list, not Home.
 await p.locator('[data-entry="ENTRY.TOOLKIT"]').click();await p.locator('[data-scact="open-editor"]').first().click();await p.locator('[data-nav="settings"]').click();await exit();assert.ok(await p.locator('[data-od-id="scenario-editor"]').count());await exit();assert.ok(await p.locator('[data-od-id="scenario-list"]').count());
 await p.reload();await p.locator('[data-act="longer-explorations"]').waitFor();assert.equal(await p.evaluate(()=>NOTES.all().length),1);assert.equal(await p.evaluate(id=>EXPLORATIONS.data.gems[id].aspect,gid),'My curiosity');
 assert.deepEqual(errors,[]);console.log('PASS: real pointer drags (torch, leaf, bookmark, face); unlimited stories; notebook photo/text save; three check-ins; nested scenario Exit; reload persistence.');await b.close();
})().catch(e=>{console.error(e);process.exit(1)});



