const {chromium}=require('C:/Users/hurri/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path');
(async()=>{const b=await chromium.launch({headless:true,channel:'msedge'});const p=await b.newPage({viewport:{width:1000,height:1100}});const out={};
await p.goto('http://127.0.0.1:4173/app/');await p.locator('[data-act="longer-explorations"]').waitFor();await p.evaluate(()=>document.fonts.ready);
async function snap(key,sel='.view'){await p.mouse.move(0,0);await p.waitForTimeout(300);out[key]=await p.locator(sel).evaluate(root=>{const r=root.getBoundingClientRect();const rect=e=>{const z=e.getBoundingClientRect();return {x:z.x-r.x,y:z.y-r.y,w:z.width,h:z.height}};return {w:r.width,h:r.height,items:[...root.querySelectorAll('*')].filter(e=>!e.closest('svg')&&e.getBoundingClientRect().width&&getComputedStyle(e).visibility!=='hidden').map(e=>{const s=getComputedStyle(e);return {tag:e.tagName,cls:e.className,id:e.id,action:e.dataset.new||e.dataset.ract||e.dataset.nact||e.dataset.act||e.dataset.nav||'',key:e.dataset.id||e.dataset.value||'',...rect(e),text:e.tagName==='TEXTAREA'?e.placeholder:[...e.childNodes].filter(n=>n.nodeType===3).map(n=>n.textContent).join('').trim(),src:e.tagName==='IMG'?e.getAttribute('src'):null,font:s.fontFamily,size:parseFloat(s.fontSize),weight:s.fontWeight,line:parseFloat(s.lineHeight),color:s.color,bg:s.backgroundColor,display:s.display};})};});}
async function exit(){await p.locator('[data-nav="exit"]').click()};async function open(action){await p.locator(`[data-ract="${action}"]`).first().click()};
await snap('home');await p.locator('[data-act="longer-explorations"]').click();await snap('longer');
await open('open-practice');await snap('garden');await p.locator('[data-new="garden-category"]').first().click();await p.locator('[data-new="garden-slot"]').first().click();await snap('leaf-dialog','dialog');await p.locator('[data-new="close-modal"]').click();await p.locator('[data-new="garden-language"]').first().click();await snap('language-dialog','dialog');await p.locator('[data-new="close-modal"]').click();await exit();
await open('open-lamp-room');await snap('spaces');await p.locator('[data-new="space"]').first().click();await snap('space-dialog','dialog');await p.locator('[data-new="close-modal"]').click();await exit();
await open('open-explore');await snap('gems');await p.locator('.movable-torch').focus();for(let i=0;i<15;i++)await p.keyboard.press('ArrowUp');await p.locator('.gem-target.lit').first().click();await snap('gem-dialog','dialog');await p.locator('[data-new="close-modal"]').click();await exit();
await open('open-story');await snap('story');await p.locator('[data-new="story-shelf"]').click();await snap('shelf');await exit();
await open('open-influence');await snap('influences');await exit();await p.locator('[data-ract="open-belonging"] span').click();await snap('contracts');await p.locator('[data-new="contract"]').first().click();await snap('contract-dialog','dialog');await p.locator('[data-new="close-modal"]').click();await exit();await exit();
await p.evaluate(()=>UI.renderMoments());await snap('notebook');await p.locator('[data-new="collection"]').click();await snap('collection');await p.locator('[data-nav="settings"]').click();await snap('settings');
fs.writeFileSync(path.resolve(__dirname,'../../design-reference/runtime-screens.json'),JSON.stringify(out,null,2));console.log(Object.keys(out));await b.close();})().catch(e=>{console.error(e);process.exit(1)});
